### ISSUE TITLE
Sonos controller name with national characters

### ISSUE THREAD

**Issue by kgn3400** [karimkaylani/alfred-sonoscontroller#1]
Hi,

Great workflow, but I get an error when my Sonos controller name contains national characters:

<img width="593" alt="Skærmbillede 2020-04-28 kl  17 50 51" src="https://user-images.githubusercontent.com/17993863/80508836-d45a7400-8978-11ea-8121-a7c6ff1f8c9b.png">

Best regards
Kurt

**Comment by karimkaylani** [comment]
Thanks so much for reporting this! This is now fixed in the newest [release](https://github.com/karimkaylani/alfred-sonoscontroller/releases/latest/download/sonoscontroller.alfredworkflow).

You can also update by typing `soco workflow:update` into your alfred search bar.
