### ISSUE TITLE
Keyword errors

### ISSUE THREAD

**Issue by sniarn** [karimkaylani/alfred-sonoscontroller#4]
Many keywords result in a workflow error. The error differs depending on the keyword, so there's a whole bunch of issues here.

<img width="729" alt="image" src="https://user-images.githubusercontent.com/4957636/81483551-5a12d500-923f-11ea-9fdf-179df1edc38d.png">

**Comment by karimkaylani** [comment]
This is now fixed in the [latest release](https://github.com/karimkaylani/alfred-sonoscontroller/releases/tag/1.3.1)

Thanks for reporting it :)
